// Code generated by "enumer -type=AccountRole -json -yaml -text -transform=snake -trimprefix=Acc"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
)

const _AccountRoleName = "normalmain_system_witnesssecond_system_witnessuser_witnesscouncilcontract"

var _AccountRoleIndex = [...]uint8{0, 6, 25, 46, 58, 65, 73}

func (i AccountRole) String() string {
	if i < 0 || i >= AccountRole(len(_AccountRoleIndex)-1) {
		return fmt.Sprintf("AccountRole(%d)", i)
	}
	return _AccountRoleName[_AccountRoleIndex[i]:_AccountRoleIndex[i+1]]
}

var _AccountRoleValues = []AccountRole{0, 1, 2, 3, 4, 5}

var _AccountRoleNameToValueMap = map[string]AccountRole{
	_AccountRoleName[0:6]:   0,
	_AccountRoleName[6:25]:  1,
	_AccountRoleName[25:46]: 2,
	_AccountRoleName[46:58]: 3,
	_AccountRoleName[58:65]: 4,
	_AccountRoleName[65:73]: 5,
}

// AccountRoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AccountRoleString(s string) (AccountRole, error) {
	if val, ok := _AccountRoleNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AccountRole values", s)
}

// AccountRoleValues returns all values of the enum
func AccountRoleValues() []AccountRole {
	return _AccountRoleValues
}

// IsAAccountRole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AccountRole) IsAAccountRole() bool {
	for _, v := range _AccountRoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AccountRole
func (i AccountRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AccountRole
func (i *AccountRole) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AccountRole should be a string, got %s", data)
	}

	var err error
	*i, err = AccountRoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AccountRole
func (i AccountRole) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AccountRole
func (i *AccountRole) UnmarshalText(text []byte) error {
	var err error
	*i, err = AccountRoleString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for AccountRole
func (i AccountRole) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for AccountRole
func (i *AccountRole) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = AccountRoleString(s)
	return err
}
