// Code generated by "stringer -type SyncMode"; DO NOT EDIT.

package types

import "strconv"

const _SyncMode_name = "MODE_FULL_BEGINMODE_DIFF_BEGINMODE_SINGLE_BEGINMODE_SINGLE_BEHINDMODE_SINGLE_POINT_HASHMODE_SINGLE_POINT_NUMBER"

var _SyncMode_index = [...]uint8{0, 15, 30, 47, 65, 87, 111}

func (i SyncMode) String() string {
	if i >= SyncMode(len(_SyncMode_index)-1) {
		return "SyncMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SyncMode_name[_SyncMode_index[i]:_SyncMode_index[i+1]]
}
